<script>
import VueTimeline from '../Sous-vues/Timeline.vue';

export default {
  components: {
    VueTimeline
  },
  data() {
    return {
      afficherVueTimeline: false
    };
  },
  methods: {
    afficherTimeline() {
      this.afficherVueTimeline = !this.afficherVueTimeline;
    },
    // ActiverMusique() {
    //   const audio = new Audio('/musiques/secunda.mp3');
    //   if(
    //   document.getElementById('LogoMusique').src==='/img/sonCoupe.png'
    //   ) {
    //     audio.play();
    //     document.getElementById('LogoMusique').src='/img/sonActive.png';
    //   } else {
    //     audio.pause();
    //     document.getElementById('LogoMusique').src='/img/sonCoupe.png';
    //   }
    // }
  }
};
</script>

<template>
  <img alt='Welcome Home traveler, been a long time. Take a sit' src="/img/gifChevalier.gif" id="background">
  <div>
    <h1 class="text-focus-in"> Bienvenue voyageur, <br> N'hésitez pas, prenez place près de ce feu <br> Vous devez être
      exténué de votre long périple
      <br>
      Faites comme chez vous, je serai votre hôte pour le temps qu'il vous plaira
      <br>
      Je suis Albin Caminade, ravi de vous rencontrer
    </h1>
  </div>
  <br><br><br><br><br><br><br><br>

  <div>
  <h2 id='texteAfficherTimeline' @click="afficherTimeline()"> Une petite histoire vous ferait envie ? <br> Découvrez mes avancées et découvertes de l'informatique</h2>
    <br><br>
    <VueTimeline v-if="afficherVueTimeline" />
    <br>
    <p @click="afficherTimeline()" v-if="afficherVueTimeline" id="refermerTimeline"> Refermer la timeline </p>
  </div>
    <br>

<!--    <img src="/img/sonCoupe.png" alt="Musique" id="LogoMusique" @click="ActiverMusique()">-->
</template>


<style scoped>
div {
  width: 100%;
  height: 100%;
  background-size: cover;
}

#background {
  width: 100%;
  height: 100%;
  object-fit: cover;
  position: fixed;
  bottom: 0;
  left: 0;
  z-index: -1;
  opacity: 0.5;
  filter: blur(5px);
  transform: scale(1.1);
  transition: 1s;
  animation: 10s infinite alternate;
  animation-name: move;
}

#imgfleche {
  width: 50px;
  height: 50px;
  margin: 10px;
  border-radius: 50%;
  animation: 2s infinite alternate;
  animation-name: move;
}

@font-face {
  font-family: 'CanelaBarkBoldPersonal';
  src: url('/css/fonts/CanelaBarkBoldPersonal.ttf');
}

h1 {
  font-family: 'CanelaBarkBoldPersonal', serif;
  font-weight: bold;
  font-size: 50px;
  -webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
  animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

.timeline {
  display: none;
}
#texteAfficherTimeline {
  cursor: pointer;
  user-select: none;
}
#refermerTimeline {
  cursor: pointer;
  user-select: none;
}

/*#LogoMusique {
  position: fixed;
  bottom: 0;
  right:10px;
  margin: 10px;
  width: 50px;
  height: 50px;
}
#LogoMusique:hover {
  cursor: pointer;
}*/

/* ----------------------------------------------
 * Generated by Animista on 2024-2-13 0:43:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}

@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}

.text-focus-in {
  -webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
  animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}


</style>

